version: '3'
services:
  requestor-data-api:
    env_file: .env
    build:
      context: .
      dockerfile: src/main/docker/application/Dockerfile
      args:
        artifact: requestor-data-api
        version: 0.0.1-SNAPSHOT
    command: /app/wait-for.sh ${RABBITMQ_HOST}:${RABBITMQ_PORT} -- java -Dspring.profiles.active=dev -jar /app/requestor-data-api.jar
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq-service
  rabbitmq-service:
    image: 'rabbitmq:management'
    env_file: .env
    ports:
      - '5672:5672'
      - '15672:15672'
  minio-server:
    env_file: .env
    build:
      context: .
      dockerfile: src/main/docker/minio/Dockerfile
    volumes:
      - minio-data:/data
    command: /mbin/wait-for-it.sh ${RABBITMQ_HOST}:${RABBITMQ_PORT} -- minio server --config-dir /minio /data
    ports:
      - '9000:9000'
    depends_on:
      - rabbitmq-service
  minio-initializer:
    env_file: .env
    build:
      context: .
      dockerfile: src/main/docker/mc/Dockerfile
    command: /mbin/wait-for-it.sh minio-server:9000 -- sh /mbin/minio-initializer.sh
    depends_on:
      - minio-server

volumes:
  minio-data:
