version: '3'
services:
  requestor-data-api:
    env_file: .env
    build:
      context: .
      dockerfile: src/main/docker/application/Dockerfile
      args:
        artifact: requestor-data-api
        version: 0.0.1-SNAPSHOT
    command: /app/wait-for.sh cassandra-service:9042 -t 0 -- java -Dspring.profiles.active=dev -jar /app/requestor-data-api.jar
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq-service
      - cassandra-service
  rabbitmq-service:
    image: 'rabbitmq:management'
    env_file: .env
    ports:
      - '5672:5672'
      - '15672:15672'
  minio-server:
    env_file: .env
    build:
      context: .
      dockerfile: src/main/docker/minio/Dockerfile
    volumes:
      - minio-data:/data
    command: /mbin/wait-for-it.sh ${RABBITMQ_HOST}:${RABBITMQ_PORT} -- minio server --config-dir /minio /data
    ports:
      - '9000:9000'
    depends_on:
      - rabbitmq-service
  minio-initializer:
    env_file: .env
    build:
      context: .
      dockerfile: src/main/docker/mc/Dockerfile
    command: /mbin/wait-for-it.sh minio-server:9000 -- sh /mbin/minio-initializer.sh
    depends_on:
      - minio-server
  cassandra-service:
    build:
      context: .
      dockerfile: src/main/docker/cassandra/Dockerfile
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
  cassandra-initializer:
    build:
      context: .
      dockerfile: src/main/docker/cassandra/Dockerfile
    command: wait-for-it.sh cassandra-service:9042 -t 0 -- cassandra-initializer.sh
    depends_on:
      - cassandra-service

volumes:
  minio-data:
