spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

cassandra:
  port: ${CASSANDRA_PORT}
  keyspace: ${CASSANDRA_KEYSPACE}
  contactpoints: ${CASSANDRA_CONTACTPOINTS}
  base-packages: ${CASSANDRA_BASE_PACKAGES}
